vim.o.tgc = true
vim.o.bg = "dark"
vim.api.nvim_set_hl(0, "Removed", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Added", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Changed", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#d19a66", fg = "#353b45" })
vim.api.nvim_set_hl(0, "NvDashButtons", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "NvDashAscii", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "LazyProgressDone", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyReasonImport", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonSource", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "LazyReasonCmd", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "LazyReasonRuntime", { fg = "#81A1C1" })
vim.api.nvim_set_hl(0, "LazyReasonStart", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonEvent", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LazyCommitIssue", { fg = "#ff75a0" })
vim.api.nvim_set_hl(0, "LazyTaskOutput", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonKeys", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LazyOperator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonFt", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "LazySpecial", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "LazyNoCond", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyCommit", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyUrl", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyDir", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyValue", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LazyReasonPlugin", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyH2", { bold = true, underline = true, fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyButton", { fg = "#888c94", bg = "#282c34" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#1b1f27" })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WinBar", { bg = "NONE" })
vim.api.nvim_set_hl(0, "healthSuccess", { fg = "#1e222a", bg = "#98c379" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#252931" })
vim.api.nvim_set_hl(0, "Cursor", { bg = "#abb2bf", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "Conceal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = "#e5c07b", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "TooLong", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Substitute", { bg = "#e5c07b", fg = "#353b45" })
vim.api.nvim_set_hl(0, "Question", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#252931", fg = "#6f737b" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DevIconDefault", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimInternalError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = "#42464e", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#42464e" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "MatchParen", { link = "MatchWord" })
vim.api.nvim_set_hl(0, "MatchWord", { fg = "#abb2bf", bg = "#42464e" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#3e4451" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "Search", { bg = "#e5c07b", fg = "#353b45" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#31353d" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#545862" })
vim.api.nvim_set_hl(0, "ErrorMsg", { bg = "#1e222a", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Error", { bg = "#e06c75", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#545862" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "NvDashFooter", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#1e222a", bg = "#61afef" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#42464e" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Normal", { bg = "#1e222a", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Title", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "LazyH1", { fg = "#1e222a", bg = "#98c379" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#252931" })
