vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#6f737b", bg = "#252931" })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = "#98c379", fg = "#1e222a" })
