vim.api.nvim_set_hl(0, "NvimTreeRootFolder", { bold = true, fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", { bold = true, fg = "#e7c787" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "#1b1f27" })
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#2c3037" })
vim.api.nvim_set_hl(0, "NvimTreeGitDirty", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeFolderArrowOpen", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { fg = "#1b1f27" })
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeGitNew", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvimTreeWindowPicker", { bg = "#252931", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", { bg = "#1b1f27", fg = "#1b1f27" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticHintFolderHL", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticHintFileHL", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticWarnFolderHL", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticWarnFileHL", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticInfoFolderHL", { link = "DiagnosticNormal" })
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticInfoFileHL", { link = "DiagnosticNormal" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticErrorFolderHL", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticErrorFileHL", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NvimTreeGitIgnored", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "NvimTreeNormalNC", { bg = "#1b1f27" })
vim.api.nvim_set_hl(0, "NvimTreeFolderArrowClosed", { fg = "#565c64" })
