vim.api.nvim_set_hl(0, "WhichKeySeparator", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "WhichKey", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "WhichKeyValue", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = "#e06c75" })
