vim.api.nvim_set_hl(0, "NvChAsciiHeader", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvChSection", { bg = "#252931" })
vim.api.nvim_set_hl(0, "NvChHeading", { bold = true, fg = "#1e222a", bg = "#61afef" })
vim.api.nvim_set_hl(0, "NvChHeadblue", { bg = "#61afef", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadred", { bg = "#e06c75", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadgreen", { bg = "#98c379", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadyellow", { bg = "#e7c787", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadorange", { bg = "#fca2aa", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadbaby_pink", { bg = "#DE8C92", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadpurple", { bg = "#de98fd", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadwhite", { bg = "#abb2bf", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadcyan", { bg = "#a3b8ef", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadvibrant_green", { bg = "#7eca9c", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "NvChHeadteal", { bg = "#519ABA", fg = "#1e222a" })
