vim.api.nvim_set_hl(0, "Operator", { sp = "none", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "Number", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "Special", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "Identifier", { sp = "none", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Type", { sp = "none", fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "String", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "StorageClass", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Variable", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Label", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Function", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Float", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "Define", { sp = "none", fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Character", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Todo", { bg = "#353b45", fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Tag", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Include", { fg = "#61afef" })
