" 窗口大小
set columns=90 lines=45

" 字体设置
if has("win32") || has("win64")
    set linespace=0
    set guifont=Consolas:h10:cDEFAULT
    set guifontwide=Microsoft_YaHei_Mono:h10:cDEFAULT
elseif has("mac")
    set guifont=Menlo:h12
else
    set guifont=monospace\ 9
endif

" 菜单栏
set guioptions-=m
" 使用非 gui 的标签页栏更美观，
set guioptions-=e
" 工具栏
set guioptions-=T
" 滚动条
set guioptions-=r
set guioptions-=L
noremap <silent> <F10> :call <SID>SwitchGuiOpt()<CR>
function! s:SwitchGuiOpt()
    " 'mT' -> 'T' -> '' -> 'mT'
    if &guioptions =~# 'T' && &guioptions =~# 'm'
        " 菜单栏和工具栏都有
        set guioptions-=m
    elseif &guioptions =~# 'T'
        " 只有工具栏
        set guioptions-=T
    elseif &guioptions =~# 'm'
        " 只有菜单栏
        set guioptions-=m
    else
        " 菜单栏和工具栏都没有
        set guioptions+=T
        set guioptions+=m
    endif
endfunction

" 启动时窗口的位置
"winpos 230 230

" 禁用闪屏
"set vb t_vb=

" 显示行号
set number

" 输入法打开时改变高亮
"if has('multi_byte_ime')
    "highlight Cursor guibg=Green guifg=NONE
    "highlight CursorIM guibg=Purple guifg=NONE
"endif

if has('gui_macvim')
    " macvim 如果显示滚动条的话，标签也换的时候会有刷新问题
    set guioptions-=r
    set guioptions-=L
    nnoremap <silent> <D-Left> :tabNext<CR>
    nnoremap <silent> <D-Right> :tabnext<CR>
    tnoremap <silent> <D-Left> <C-w>:tabNext<CR>
    tnoremap <silent> <D-Right> <C-w>:tabnext<CR>
    inoremap <silent> <D-Left> <C-\><C-o>:tabNext<CR>
    inoremap <silent> <D-Right> <C-\><C-o>:tabnext<CR>
endif

if has('terminal')
    " why not work?
    "tnoremap <M-.> <C-w>:<C-u>call term_sendkeys(bufnr('%'), "\<Esc>.")<CR>
    func! s:tmap_meta(key)
        call term_sendkeys(bufnr('%'), "\<Esc>" . a:key)
    endfunc
    func! s:setup_terminal_meta()
        for i in range(65, 90) + range(97, 122)
            exec "tnoremap <silent> <M-.> \<C-w>:call \<SID>tmap_meta('.')\<CR>"
        endfor
    endfunc
    call s:setup_terminal_meta()
endif

" vi:set et sts=4 sw=4:
