vim.api.nvim_set_hl(0, "Added", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Changed", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#30343C" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#757981" })
vim.api.nvim_set_hl(0, "Conceal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#282c34", bg = "#abb2bf" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#30343C" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DevIconDefault", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Error", { fg = "#282c34", bg = "#e06c75" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#e06c75", bg = "#282c34" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "FloatTitle", { fg = "#abb2bf", bg = "#484C54" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "Folded", { fg = "#757981", bg = "#30343C" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#353b45", bg = "#d19a66" })
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#383C44", fg = "#8f9299" })
vim.api.nvim_set_hl(0, "LazyCommit", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyCommitIssue", { fg = "#ff75a0" })
vim.api.nvim_set_hl(0, "LazyDir", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyH1", { bg = "#98c379", fg = "#282c34" })
vim.api.nvim_set_hl(0, "LazyH2", { underline = true, fg = "#e06c75", bold = true })
vim.api.nvim_set_hl(0, "LazyNoCond", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyOperator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyProgressDone", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyReasonCmd", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "LazyReasonEvent", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LazyReasonFt", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "LazyReasonImport", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonKeys", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LazyReasonPlugin", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyReasonRuntime", { fg = "#81A1C1" })
vim.api.nvim_set_hl(0, "LazyReasonSource", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "LazyReasonStart", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazySpecial", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "LazyTaskOutput", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyUrl", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyValue", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#484C54" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "MatchParen", { link = "MatchWord" })
vim.api.nvim_set_hl(0, "MatchWord", { bg = "#484C54", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Normal", { fg = "#abb2bf", bg = "#282c34" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#22262E" })
vim.api.nvim_set_hl(0, "NvDashAscii", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvDashButtons", { fg = "#757981" })
vim.api.nvim_set_hl(0, "NvDashFooter", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimInternalError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "#383C44" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#383C44" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#61afef", fg = "#282c34" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#484C54" })
vim.api.nvim_set_hl(0, "Question", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "Removed", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Search", { fg = "#353b45", bg = "#e5c07b" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#545862" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Substitute", { fg = "#353b45", bg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Title", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "TooLong", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#3e4451" })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "WildMenu", { fg = "#e06c75", bg = "#e5c07b" })
vim.api.nvim_set_hl(0, "WinBar", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#3B3F47" })
vim.api.nvim_set_hl(0, "healthSuccess", { bg = "#98c379", fg = "#282c34" })
vim.o.bg = "dark"
vim.o.tgc = true
