vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DiffAdded", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#757981" })
vim.api.nvim_set_hl(0, "DiffChangeDelete", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffModified", { fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DiffRemoved", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffText", { fg = "#abb2bf", bg = "#30343C" })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = "#DE8C92" })
vim.api.nvim_set_hl(0, "gitcommitBranch", { fg = "#d19a66", bold = true })
vim.api.nvim_set_hl(0, "gitcommitComment", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitDiscarded", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitDiscardedFile", { fg = "#e06c75", bold = true })
vim.api.nvim_set_hl(0, "gitcommitDiscardedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitHeader", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "gitcommitOverflow", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "gitcommitSelected", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitSelectedFile", { fg = "#98c379", bold = true })
vim.api.nvim_set_hl(0, "gitcommitSelectedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitSummary", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "gitcommitUnmergedFile", { fg = "#e06c75", bold = true })
vim.api.nvim_set_hl(0, "gitcommitUnmergedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitUntracked", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitUntrackedFile", { fg = "#e5c07b" })
