vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#757981", bg = "#30343c" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = "#3d4149" })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = "#3d4149" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = "#3d4149" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = "#98c379", fg = "#282c34" })
