vim.api.nvim_set_hl(0, "MasonHeader", { fg = "#282c34", bg = "#e06c75" })
vim.api.nvim_set_hl(0, "MasonHeaderSecondary", { link = "MasonHighlightBlock" })
vim.api.nvim_set_hl(0, "MasonHighlight", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "MasonHighlightBlock", { bg = "#98c379", fg = "#282c34" })
vim.api.nvim_set_hl(0, "MasonHighlightBlockBold", { link = "MasonHighlightBlock" })
vim.api.nvim_set_hl(0, "MasonMuted", { fg = "#757981" })
vim.api.nvim_set_hl(0, "MasonMutedBlock", { bg = "#383c44", fg = "#757981" })
