vim.api.nvim_set_hl(0, "MasonHeader", { bg = "#e06c75", fg = "#282c34" })
vim.api.nvim_set_hl(0, "MasonHeaderSecondary", { link = "MasonHighlightBlock" })
vim.api.nvim_set_hl(0, "MasonHighlight", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "MasonHighlightBlock", { fg = "#282c34", bg = "#98c379" })
vim.api.nvim_set_hl(0, "MasonHighlightBlockBold", { link = "MasonHighlightBlock" })
vim.api.nvim_set_hl(0, "MasonMuted", { fg = "#757981" })
vim.api.nvim_set_hl(0, "MasonMutedBlock", { fg = "#757981", bg = "#383C44" })
