vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticErrorFileHL", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticErrorFolderHL", { link = "DiagnosticError" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticHintFileHL", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticHintFolderHL", { link = "DiagnosticHint" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticInfoFileHL", { link = "DiagnosticNormal" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticInfoFolderHL", { link = "DiagnosticNormal" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticWarnFileHL", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NvimTreeDiagnosticWarnFolderHL", { link = "DiagnosticWarn" })
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { fg = "#22262E" })
vim.api.nvim_set_hl(0, "NvimTreeFolderArrowClosed", { fg = "#5C626A" })
vim.api.nvim_set_hl(0, "NvimTreeFolderArrowOpen", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeGitDeleted", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeGitDirty", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimTreeGitIgnored", { fg = "#757981" })
vim.api.nvim_set_hl(0, "NvimTreeGitNew", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", { fg = "#363a41" })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "#22262E" })
vim.api.nvim_set_hl(0, "NvimTreeNormalNC", { bg = "#22262E" })
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvimTreeRootFolder", { fg = "#e06c75", bold = true })
vim.api.nvim_set_hl(0, "NvimTreeSpecialFile", { fg = "#e7c787", bold = true })
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", { fg = "#22262E", bg = "#22262E" })
vim.api.nvim_set_hl(0, "NvimTreeWindowPicker", { fg = "#e06c75", bg = "#30343C" })
