vim.api.nvim_set_hl(0, "@annotation", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@character", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@comment", { fg = "#5c6370" })
vim.api.nvim_set_hl(0, "@comment.danger", { bg = "#e06c75", fg = "#30343c" })
vim.api.nvim_set_hl(0, "@comment.note", { bg = "#61afef", fg = "#282c34" })
vim.api.nvim_set_hl(0, "@comment.todo", { bg = "#abb2bf", fg = "#4b5263" })
vim.api.nvim_set_hl(0, "@comment.warning", { bg = "#d19a66", fg = "#30343c" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@constant.macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@definition", { sp = "#565c64", underline = true })
vim.api.nvim_set_hl(0, "@diff.delta", { fg = "#757981" })
vim.api.nvim_set_hl(0, "@diff.minus", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@diff.plus", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@error", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@function", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.call", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@function.method", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.directive", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.exception", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "Include" })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.storage", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@markup.heading", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@markup.italic", { italic = true })
vim.api.nvim_set_hl(0, "@markup.link", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = "#d19a66", underline = true })
vim.api.nvim_set_hl(0, "@markup.list", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@markup.quote", { bg = "#30343c" })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
vim.api.nvim_set_hl(0, "@markup.strong", { bold = true })
vim.api.nvim_set_hl(0, "@markup.underline", { underline = true })
vim.api.nvim_set_hl(0, "@module", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@number", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@number.float", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@property", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@reference", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@scope", { bold = true })
vim.api.nvim_set_hl(0, "@string", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@string.regex", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@symbol", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@tag", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@text", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@text.emphasis", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@text.strike", { fg = "#be5046", strikethrough = true })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@variable.member.key", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#e06c75" })
