general.import = [
    # uncomment the flavour you want below:
    #"~/.config/alacritty/catppuccin-latte.toml",
    #"~/.config/alacritty/catppuccin-frappe.toml",
    #"~/.config/alacritty/catppuccin-macchiato.toml",
    #"~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/gruvbox.toml",
]

colors.draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM_PROGRAM = "alacritty"

[font]
size = 12.0

[font.normal]
# NOTE: 设置顺序很重要, normal 必须在 bold italic 之前
family = "SFMono Nerd Font"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = false
mods = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
option_as_alt = "Both"
resize_increments = true

[window.dimensions]
columns = 130
lines = 40

[window.padding]
x = 1 # 横轴 border
y = 0 # 纵轴 border

[keyboard]
bindings = [
    { key = 'Right',    mods = 'Command',       action = 'SelectNextTab' },
    { key = 'Left',     mods = 'Command',       action = 'SelectPreviousTab' },
    { key = 'Tab',      mods = 'Control',       action = 'SelectNextTab' },
    { key = 'Tab',      mods = 'Control|Shift', action = 'SelectPreviousTab' },
]
