#!/bin/bash
# custom shell config

stty -ixon

##############################  Custom Env Var  ##############################
# JAVA 程序字体渲染设置
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'

# 256
if [ -n "$TMUX" ]; then
    export TERM=screen-256color
else
    export TERM=xterm-256color
fi

##############################  Custom Alias    ##############################

alias rm="rm -I"
alias checkinstallun='checkinstall --install=no'
#alias zhong="zhcon --utf8 --drv=vga"
alias cao="sudo arpspoof -i eth0 -t 192.168.1.101 192.168.1.1"
alias eng="export LANGUAGE=en_US.UTF-8 LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8"
alias zho="export LANGUAGE=zh_CN.UTF-8 LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8"
alias zhong="export LANG=zh_CN.UTF-8"
alias gvim="gvim -f"

alias killall9="killall -KILL"
complete -F _killall killall9

alias ctags-cpp="ctags --c++-kinds=+p --fields=+iaS --extra=+q --languages=c++"
alias myctags="ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --languages=c,c++"
alias myvlctags2="CTAGS_GLOBAL_MACROS_FILES=global.h,global.hpp vlctags2 --excmd=pattern --sort=no --fields=aKmSsnit --c-kinds=+px --C++-kinds=+px"
alias fbtermx="fbterm -i fbterm_ucimf"
# 代理转发
alias sshawsN="ssh -i ~/.ssh/fanhe_aws.pem ubuntu@ec2-54-200-70-206.us-west-2.compute.amazonaws.com -Nf -D 1080"
# 反弹端口
alias sshawsR="ssh -i ~/.ssh/fanhe_aws.pem ubuntu@ec2-54-200-70-206.us-west-2.compute.amazonaws.com -Nf -R 10086:127.0.0.1:22"
alias sshaws="ssh -i ~/.ssh/fanhe_aws.pem ubuntu@ec2-54-200-70-206.us-west-2.compute.amazonaws.com"

complete -o filenames -F _apt_get apt-axel-get

##############################  xmms2 Alias ##############################
alias xmms2-repeat_one_switch='[[ `xmms2 config_list | grep "repeat_one"` == "playlist.repeat_one = 0" ]] && xmms2 config playlist.repeat_one 1 || xmms2 config playlist.repeat_one 0'
alias xmms2-shuffle='xmms2 jump +"$((RANDOM%100))"'

##############################  Custom Func ##############################

findn ()
{
    find . -iname "*$1*"
}

httpproxy ()
{
    export http_proxy="http://$1"
}

bakfile ()
{
local n=0
local fname

    for i in "$@"; do
        fname="$i.bak"
        
        if [[ -e "$fname" ]]; then
            n=1
            while [[ -e "$fname.$n" ]]; do
                let n++
            done
            fname="$fname.$n"
        fi
        
        cp "$i" "$fname"
    done
}

# Use VIm as man pager
vman () {
    export PAGER="/bin/sh -c \"unset PAGER;col -b -x | \
                     vim -R -c 'set ft=man nomod nolist' -c 'map q :q<CR>' \
                     -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
                     -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""

    # invoke man page
    man $1

    # we muse unset the PAGER, so regular man pager is used afterwards
    unset PAGER
}

# vi:set et sts=4:
